### PR TITLE
Grammatical Tweaks to Book

### PR DESCRIPTION
**Pull request by KodrAus**
I just thought I'd throw up a PR of my personal grammatical tweaks as I read :)

As with all things language, what's 'most correct' is always up for debate, but hopefully others will chime in too. I'm just nitting on simple things.

I'll try to keep commits small for cherry-picking. Thanks for the great work in putting this book together!

### CODE REVIEW

**Comment by KodrAus** [comment]
@MichaelHirn do you have any thoughts on my suggestions so far?

**Comment by MichaelHirn** [comment]
Thank you so much - I appreciate your suggestions and editorial changes very much!
They make a lot of sense! You are really helping me out here in putting this book together.

I just saw that you are changing the `.html` files, but you might rather edit the `.md` files in the `/doc/src` directory. Running `~/.cargo/bin/mdbook build ./doc` turns them into the `.html`  files in the `/doc/book` directory. Sorry, that I didn't explicitly point this out earlier.

**Comment by MichaelHirn** [comment]
But if you don't want your commits to be merged, editing the `.html` files is not a problem. I can copy it over manually later.

**Comment by KodrAus** [comment]
Ah I hadn't realised! I'll shift my changes over to the md files and work on those from now on. That's what I get for being lazy and working directly on GitHub rather than using the tools properly.

**Comment by MichaelHirn** [comment]
I just wanted to thank you for porting it to the `.md` files. That is huge.

I followed along your changes and like them very much. We are preparing for the 0.2.1 release right now and I can't wait to merge your improvements in. Can you brief me on your plans?

Also let me know if you have any high-level feedback (regarding the book) that you would like to share?

**Comment by KodrAus** [comment]
No problem :)

Basically I'm just trying to run through and clarify a few things as someone who isn't intimately familiar with Leaf, without really adding or removing any content. I'm guessing the theory of Leaf would be pretty stable and not much will change there, but Leaf itself will change so the book will need updating to keep up with that.

So I think keeping the book focussed on concepts, made concrete with some samples and referring to the docs for more detailed technical info would prevent you having to duplicate too much content between them, which looks like the way you've already done it. It's an excellent and important piece of work you've done that helps mature Leaf.

I'll keep going through and copyediting as I read, and maybe on a second pass we can think about things at a higher level; where new sections and maybe diagrams would be helpful.

Are you planning to merge for `0.2.1`? If so, do you have a rough date so I can make sure I've been through the whole thing by then?

**Comment by MichaelHirn** [comment]
Thank you for the feedback.

I am glad, that the intention, sticking to the high-level concepts, so the book is a bit more timeless and doesn't require a change every time something in leaf changes, was recognizable.

I have planned to introduce the Leaf book with the 0.2.1 release. Which is planned for the middle next week. But no pressure about finishing your editing in the next days. I am happy to merge, what's there and the rest could be done in a second PR. That way, people would have at least for the first few chapters are more clear and coherent reading experience, thanks to your commits.

**Comment by KodrAus** [comment]
Sounds good. I've made some changes to Layer Lifecycle. I might stop there for now so you can go through everything and merge the changes you want to include.

I haven't done a proper job of Layer Lifecycle yet though, so if you're not totally happy with what I've done there then I'll revisit it.

Best of luck with the next release!

**Comment by MichaelHirn** [comment]
Thank you, @KodrAus. I actually like the layer lifecycle changes very much. I think I will take all of your commits :)

**Comment by KodrAus** [comment]
Thanks! Glad I could be helpful :)

**Pull request merged**
